### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by Bucchiman** [Bucchiman/sh#3]
# ToDo
- [] mywork setting
- [] specific file path location
- [] symbolic link path with only one module
- [] codes for each language
